config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:index, :show, :update]
  resources :follows, only: [:index, :create, :update, :destroy]
  resources :posts, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :likes, only: [:create, :destroy]

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followee, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :image

  validates_presence_of(:body)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :followed_users, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :followees, through: :followed_users

  has_many :following_users, foreign_key: :followee_id, class_name: "Follow", dependent: :destroy
  has_many :followers, through: :following_users

  has_one_attached :photo

  validates_presence_of(:name)

  # As per documentation here: https://github.com/zquestz/omniauth-google-oauth2?tab=readme-ov-file#devise

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
        user = User.create(name: data['name'],
           email: data['email'],
           password: Devise.friendly_token[0,20],
           provider: access_token.provider,
           uid: access_token.uid,
           photo_url: data['image']
        )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(current_user.id)
    comment = user.comments.build(comment_params)
    if comment.save!
      redirect_back_or_to(root_path)
    else
      flash[:alert] = 'Something went wrong'
      redirect_to root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :content)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def index
    f = Follow.where(followee_id: current_user.id)
    @followers = f.where(status: 'ok')
    @pending = f.where(status: 'pending')
    @followees = Follow.where(follower_id: current_user.id)
  end

  def create
    follow = Follow.where("follower_id = ? AND followee_id = ?", current_user.id, follow_params[:id])
    if follow.any?
      flash[:alert] = follow.status == 'ok' ? 'You already are following this user!' : 'You already tried following this user, please wait their response'
    else
      follow = Follow.new
      follow.follower_id = current_user.id
      follow.followee_id = follow_params[:id]
      follow.status = 'pending'
      follow.save!
    end

    redirect_back_or_to(root_path)
  end

  def update
    follow = Follow.find_by("followee_id = ? AND follower_id = ?", current_user.id, follow_params[:id])
    if follow.update(status: 'ok')
      redirect_back_or_to(root_path)
    else
      flash[:alert] = 'Something went wrong'
      render root_path, status: :unprocessable_entity
    end
  end

  def destroy
    follow = Follow.where("follower_id = ? AND followee_id = ?", current_user.id, follow_params[:id]).first
    if follow.destroy
      redirect_back_or_to(root_path)
    else
      flash[:alert] = 'Something went wrong'
      render root_path, status: :unprocessable_entity
    end
  end

  private

  def follow_params
    params.require(:user).permit(:id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!


  def create
    like = Like.where("user_id = ? AND post_id = ?", current_user.id, like_params[:id])
    if like.any?
      flash[:alert] = 'You already liked this post!'
    else
      like = Like.new
      like.user_id = current_user.id
      like.post_id = like_params[:id]
      like.save!
    end

    redirect_back_or_to(root_path)
  end

  def destroy
    like = Like.where("user_id = ? AND post_id = ?", current_user.id, like_params[:id]).first
    if like.destroy
      redirect_back_or_to(root_path)
    else
      flash[:alert] = 'Something went wrong'
      redirect_to root_path
    end
  end

  private

  def like_params
    params.require(:post).permit(:id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    allowed_users = Follow.where(follower_id: current_user.id, status: 'ok').map(&:followee_id) << current_user.id
    @posts = Post.where(user_id: allowed_users).reverse_order
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(current_user.id)
    if @user.posts.create!(post_params)
      redirect_to @user
    else
      flash[:alert] = 'Something went wrong'
      render root_path, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(post_id: @post.id)
    @likes = Like.where(post_id: params[:id]).count
  end

  private

  def post_params
    params.require(:post).permit(:body, :image_url, :image)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# As per documentation here: https://github.com/zquestz/omniauth-google-oauth2?tab=readme-ov-file#devise

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2

      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController< Devise::RegistrationsController

  def create
    super

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.with(user: @user).welcome_email.deliver_later

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
        return
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        return
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id]).reverse_order
  end

  def update
    user = User.find(current_user.id)
    if user.photo.attach(user_params[:photo])
      redirect_back_or_to(root_path)
    else
      flash[:alert] = 'Something went wrong'
      redirect_back_or_to(root_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/index.html.erb
<%= render "shared/navbar" %>

<% if @pending.any? %>
  <h1>Here are all of your pending requests</h1>
  <ul>
    <% @pending.each do |p| %>
      <li> 
        <%= link_to p.follower.name, user_path(p.follower.id) %>

        <%= form_with model: p.follower, url: follow_path(p.follower.id), method: :patch  do |form| %>
          <%= form.hidden_field :id, :value => p.follower.id %>
          <%= form.submit "Accept request" %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
<h1>Here are your followers</h1>
<% if @followers %>

  <ul>
    <% @followers.each do |f| %>
      <li>
        <%= link_to f.follower.name, user_path(f.follower.id) %>
      </li>
    <% end %>
  </ul>

<% end %>

<h1>Here are the one who follows you</h1>

<% if @followees %>
  <ul>
    <% @followees.each do |f| %>
      <% if f.status == 'ok' %>
        <li>
          <%= link_to f.followee.name, user_path(f.followee.id) %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odinbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/navbar" %>

<h1>Home</h1>
<%= link_to 'New Post', new_post_path %>
<div>
  <% if @posts %>
    <ul>
      <% @posts.each do |post| %>
        <li>
          <div class="post">
            <%= link_to post_path(post.id) do %>
                <% if !post.image_url.empty? %>
                  <img src=<%=post.image_url%>>
                  <br>
                <% elsif post.image.attached? %>
                  <img src=<%=url_for(post.image)%>>
                  <br>
                <% end %>
                <%= post.body %>
                <br>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_with model: @post do |f| %>
  <%= f.text_field :image_url, placeholder: "Image URL (Optional)" %>
  <br>
  <%= f.text_area :body, size: "50x10" %>
  <%= f.file_field :image, accept: 'image/png,image/jpeg' %>
  <br>
  <%= f.submit "Post" %>
<% end %>

app/views/posts/show.html.erb
<%= render "shared/navbar" %>

<h1><%= @post.user.name %> posted:</h1>

<% if flash[:alert] %>
  <br>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>

<div class="post">
  <% if !@post.image_url.empty? %>
    <img src=<%= @post.image_url%>>
    <br>
  <% elsif @post.image.attached? %>
    <img src=<%=url_for(@post.image)%>>
  <% end %>
  <%= @post.body %>
  <br>
  <br>
  <% like = Like.where("user_id = ? AND post_id = ?", current_user.id, @post.id) %>

  <% if like.any? %>
    <%= form_with model: @post, url: like_path, method: :delete do |form| %>
      <%= form.hidden_field :id, :value => @post.id %>
      <%= form.submit "Unlike" %>
    <% end %>
  <% else %>
    <%= form_with model: @post, url: likes_path, method: :post do |form| %>
      <%= form.hidden_field :id, :value => @post.id %>
      <%= form.submit "Like" %>
    <% end %>
  <% end %>
  <%= @likes %>
</div>
<br>
<%= form_with model: [@post, @comment] do |f| %>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= f.text_area :content, size: "40x2" %>
  <%= f.submit "Comment" %>
<% end %>

<% if @comments.any? %>
  <br>
  <br>
  <ul>
    <% @comments.each do |comment| %>
      <li>
        <div class="comment">
          <div class="commentInfo"><%= comment.user.name %>, posted at <%= comment.created_at %></div>
          <br>
          <%= comment.content %>
        </div>
        <br>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to current_user.name, user_path(current_user.id) %></li>
    <li><%= link_to "Users", users_path %></li>
    <li><%= link_to "Follows", follows_path %></li>
    <li class="log"><%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %></li>
  </ul>
</div>

app/views/users/index.html.erb
<%= render "shared/navbar" %>

<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
  <li>
    <div class="user">
      <%= link_to user.name, user_path(user.id) %>

      <% if current_user.id != user.id %>

        <% follow = Follow.where("follower_id = ? AND followee_id = ?", current_user.id, user.id) %>

        <% if !follow.any? %>

          <%= form_with model: user, url: follows_path, method: :post  do |form| %>
            <%= form.hidden_field :id, :value => user.id %>
            <%= form.submit "Follow" %>
          <% end %>
          
        <% elsif follow.first.status == 'pending' %>

          <%= form_with model: user, url: follow_path(user.id), method: :delete  do |form| %>
            <%= form.hidden_field :id, :value => user.id %>
            <%= form.submit "Cancel pending request" %>
          <% end %>

        <% else %>

          <%= form_with model: user, url: follows_path(user.id), method: :delete  do |form| %>
            <%= form.hidden_field :id, :value => user.id %>
            <%= form.submit "Unfollow" %>
          <% end %>

        <% end %>
      <% end %>
    </div>
  </li>
  <br>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= render "shared/navbar" %>

<% if @user.photo_url && !@user.provider.nil? %>
  <div class="profileImage">
    <img src=<%=@user.photo_url%> alt="profile-image">
  </div>
<% elsif !@user.photo.attached? %>
  <br>
  <br>
  <%= form_with model: @user do |form| %>
    <%= form.file_field :photo, accept: 'image/png,image/jpeg' %>
    <%= form.submit "Upload a profile image" %>
  <% end %>
<% else %>
  <br>
  <br>
  <div class="profileImage">
    <img src=<%=url_for(@user.photo)%>>
  </div>
  <%= form_with model: @user do |form| %>
    <%= form.file_field :photo, accept: 'image/png,image/jpeg' %>
    <%= form.submit "Change profile image" %>
  <% end %>
<% end %>

<h1><%= @user.name %></h1>

<% if flash[:alert] %>
  <br />
  <br />
  <div class="alert"><%= flash[:alert] %></div>
<% end %>


<% if current_user.id != @user.id %>

  <% follow = Follow.where("follower_id = ? AND followee_id = ?", current_user.id, params[:id]) %>

  <% if !follow.any? %>

    <%= form_with model: @user, url: follows_path, method: :post  do |form| %>
      <%= form.hidden_field :id, :value => @user.id %>
      <%= form.submit "Follow" %>
    <% end %>
    
  <% elsif follow.first.status == 'pending' %>

    <%= form_with model: @user, url: follow_path, method: :delete  do |form| %>
      <%= form.hidden_field :id, :value => @user.id %>
      <%= form.submit "Cancel pending request" %>
    <% end %>

  <% else %>

    <%= form_with model: @user, url: follow_path, method: :delete  do |form| %>
      <%= form.hidden_field :id, :value => @user.id %>
      <%= form.submit "Unfollow" %>
    <% end %>

  <% end %>

<% else %>
  <%= link_to 'New Post', new_post_path %>
<% end %>
<br>
<% if @posts %>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to post_path(post.id) do %>
          <div class="post">
            <% if !post.image_url.empty? %>
              <img src=<%=post.image_url%>>
              <br>
            <% elsif post.image.attached? %>
              <img src=<%=url_for(post.image)%>>
              <br>
            <% end %>
            <%= post.body %>
            <br>
            
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>